In [40]:
# Input data for OR gate
input_data = [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]

# Output labels for OR gate
output_labels = [
    0,
    1,
    1,
    1
]

print("Input Data:", input_data)
print("Output Labels:", output_labels)

Input Data: [[0, 0], [0, 1], [1, 0], [1, 1]]
Output Labels: [0, 1, 1, 1]


In [41]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras.metrics import mean_squared_error

In [51]:
model2 = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

In [42]:
model = Sequential([
    Dense(7, input_shape=(2,), activation='relu'),
    Dense(5, activation='relu'),
    Dense(3, activation='relu'),
    Dense(1, activation='sigmoid')
])

c:\Users\brian\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [43]:
model.compile(optimizer=SGD(),loss='mean_squared_error',metrics=['mean_squared_error','accuracy'])

In [44]:
import numpy as np

input_data = np.array(input_data)
output_labels = np.array(output_labels)

In [ ]:
model.fit(input_data, output_labels, batch_size=1,  epochs=2000, verbose=2)

In [46]:
model.get_weights()

[array([[ 0.12982938, -0.60041773,  0.30657095,  1.0759568 , -0.05310953,
         -0.47660753, -0.23122954],
        [-0.18204615,  0.49629265,  0.11260329,  0.85735613, -0.5380188 ,
         -0.5908161 , -0.27787977]], dtype=float32),
 array([-0.12988329,  0.00019046,  0.15757853, -0.00108893,  0.        ,
         0.        ,  0.        ], dtype=float32),
 array([[-0.00743455, -0.07775999,  0.29373938, -0.25539634, -0.21717075],
        [ 0.3968864 ,  0.55132115,  0.23195353,  0.8203928 , -0.12640041],
        [ 0.22091103, -0.13150488,  0.43649662,  0.3408372 , -0.20308137],
        [-0.70708674, -0.05747462, -0.624074  ,  1.183441  , -0.09920859],
        [-0.3553571 , -0.51723385, -0.15728766,  0.14628446, -0.19831187],
        [ 0.23772424, -0.38737607, -0.4100546 , -0.01291668, -0.20255148],
        [ 0.4322601 ,  0.4663325 ,  0.17702132,  0.6066386 ,  0.1133005 ]],
       dtype=float32),
 array([-0.03503183, -0.18898104,  0.30202475,  0.07517511,  0.        ],
       dtype=flo

In [47]:
predictions = model.predict(input_data, batch_size=1, verbose=0)
for i in predictions:
    print(round(i[0]))

0
1
1
1


### XOR

In [54]:
input_xor_data = [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]
output_xor_labels = [
    0,
    1,
    1,
    0
]
print("Input XOR Data:", input_xor_data)
print("Output XOR Labels:", output_xor_labels)

Input XOR Data: [[0, 0], [0, 1], [1, 0], [1, 1]]
Output XOR Labels: [0, 1, 1, 0]


In [60]:
model = Sequential([
    Dense(7, input_shape=(2,), activation='relu'),
    Dense(5, activation='sigmoid'),
    Dense(3, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer=SGD(),loss='mean_squared_error',metrics=['mean_squared_error','binary_accuracy'])

input_xor_data = np.array(input_xor_data)
output_xor_labels = np.array(output_xor_labels)

model.fit(input_xor_data, output_xor_labels, batch_size=1,  epochs=50, verbose=2)



c:\Users\brian\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
4/4 - 1s - 251ms/step - binary_accuracy: 0.5000 - loss: 0.2558 - mean_squared_error: 0.2558
Epoch 2/50
4/4 - 0s - 16ms/step - binary_accuracy: 0.5000 - loss: 0.2557 - mean_squared_error: 0.2557
Epoch 3/50
4/4 - 0s - 16ms/step - binary_accuracy: 0.5000 - loss: 0.2556 - mean_squared_error: 0.2556
Epoch 4/50
4/4 - 0s - 17ms/step - binary_accuracy: 0.5000 - loss: 0.2555 - mean_squared_error: 0.2555
Epoch 5/50
4/4 - 0s - 16ms/step - binary_accuracy: 0.5000 - loss: 0.2554 - mean_squared_error: 0.2554
Epoch 6/50
4/4 - 0s - 15ms/step - binary_accuracy: 0.5000 - loss: 0.2553 - mean_squared_error: 0.2553
Epoch 7/50
4/4 - 0s - 15ms/step - binary_accuracy: 0.5000 - loss: 0.2552 - mean_squared_error: 0.2552
Epoch 8/50
4/4 - 0s - 15ms/step - binary_accuracy: 0.5000 - loss: 0.2551 - mean_squared_error: 0.2551
Epoch 9/50
4/4 - 0s - 15ms/step - binary_accuracy: 0.5000 - loss: 0.2550 - mean_squared_error: 0.2550
Epoch 10/50
4/4 - 0s - 14ms/step - binary_accuracy: 0.5000 - loss: 0.2549 - mean_

In [59]:
predictions = model.predict(input_xor_data, batch_size=1, verbose=0)
for i in predictions:
    print(round(i[0]))

1
1
1
1
